/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package turmacgrupo2;

import java.beans.Beans;
import java.util.List;
import javax.swing.JOptionPane;
import turmacgrupo2.CadastroCliente;
import turmacgrupo2.CadastroFornecedor;
import turmacgrupo2.CadastroFuncionario;
import turmacgrupo2.Menu;
import turmacgrupo2.CadastroProduto;

/**
 *
 * @author pronatec3
 */
public class Cadastros extends javax.swing.JFrame {

    /**
     * Creates new form Cadastros
     */
    public Cadastros() {
        new Transparencia().TransCompFrame(this);
        initComponents();
        
         if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("turmacgrupo2?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT n FROM NivelAcesso n");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : query.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastros");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(null);

        jButton5.setBackground(new java.awt.Color(202, 237, 225));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turmacgrupo2/ghjfk.jpeg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(148, 393, 90, 83);

        jButton4.setBackground(new java.awt.Color(202, 237, 225));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turmacgrupo2/tjy9u8.jpeg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(148, 281, 90, 87);

        jButton3.setBackground(new java.awt.Color(202, 237, 225));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turmacgrupo2/kkl.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(148, 172, 90, 91);

        jButton2.setBackground(new java.awt.Color(202, 237, 225));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turmacgrupo2/jhkj.jpeg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(148, 80, 90, 74);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Informe o tipo de cadastro:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(33, 25, 294, 29);

        jLabel2.setText("FUNCIONARIO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(33, 95, 100, 14);

        jLabel3.setText("PRODUTO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(33, 187, 90, 14);

        jLabel4.setText("CLIENTE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(33, 295, 90, 14);

        jLabel5.setText("FORNECEDOR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(33, 410, 100, 14);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(714, 113, 0, 0);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(33, 113, 48, 17);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turmacgrupo2/v.jpeg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(280, 390, 80, 80);

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(580, 420, 34, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turmacgrupo2/sapatilha.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 10, 330, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(verificaAcessoFunc(jLabel2.getText(),jLabel8.getText())){
          String args[] = new String[1];
        args[0] = "Funcionario";        
        CadastroFuncionario.main(args);
        
    }else{
            JOptionPane.showMessageDialog(null, "Voce nao tem acesso!");
}
    }//GEN-LAST:event_jButton2ActionPerformed
private boolean verificaAcessoFunc(String nomeM,String codFuncionario){
        
    query=entityManager.createNamedQuery("NivelAcesso.verifiqueAcesso");
        query.setParameter("codFunc", Integer.parseInt(codFuncionario));
        query.setParameter("acesso", nomeM);
        
        List <NivelAcesso> data = query.getResultList();
        if(data.size()>0)
        {
            return true;
        }else{
            return false;
        }

    
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(verificaAcessoFunc(jLabel4.getText(),jLabel8.getText())){
        String args[] = new String[1];
      args[0] = "Clientes";
      CadastroCliente.main(args);
      
       }else{
            JOptionPane.showMessageDialog(null, "Voce nao tem acesso!");
}
    }//GEN-LAST:event_jButton4ActionPerformed
    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(verificaAcessoFunc(jLabel3.getText(), jLabel8.getText()))
        {
        String args[] = new String[1];
        args[0] = "Produto";        
        CadastroProduto.main(args); 
        }else{
            JOptionPane.showMessageDialog(null,"Voce nao tem acesso!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(verificaAcessoFunc(jLabel5.getText(), jLabel8.getText())){
        String args[] = new String[1];
        args[0] = "Cadastro de Fornecedores";        
        CadastroFornecedor.main(args);
        }else{
            JOptionPane.showMessageDialog(null, "Voce nao tem acesso!");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastros().setVisible(true);
                jLabel8.setText(args[0]);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.util.List<turmacgrupo2.NivelAcesso> list;
    private javax.persistence.Query query;
    // End of variables declaration//GEN-END:variables
}
